# Dockerfile.backend
# Stage 1: Build
FROM node:22 AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

# Stage 2: Production
FROM node:22-slim
WORKDIR /app
COPY --from=builder /app /app
RUN npm install --only=production && npm rebuild sqlite3 --build-from-source
COPY map_data.db /app/map_data.db

# Expose the backend port
EXPOSE 3000

# Start the backend server
CMD ["node", "server.js"]