# Dockerfile.frontend
# Stage 1: Build
FROM node:22 AS builder
WORKDIR /app
COPY package*.json ./map-app-client/
RUN cd map-app-client && npm install
COPY map-app-client/ ./map-app-client
RUN cd map-app-client && npm run build

# Stage 2: Production
FROM nginx:alpine
COPY --from=builder /app/map-app-client/build /usr/share/nginx/html

# Expose the frontend port
EXPOSE 3001

# Start Nginx server
CMD ["nginx", "-g", "daemon off;"]